### PR TITLE
Fix URL encoding of ds.url param

### PR DESCRIPTION
**Pull request by amacneil**

### CODE REVIEW

**Comment by amacneil** [comment]
@jtbandes after this can we publish a new release? I gave a demo today and the incorrect wss: URL tripped me up

**Comment by jtbandes** [comment]
I don't understand this change. The url works fine for me.

**Comment by jtbandes** [comment]
The `wss` vs `ws` change was made a while ago and you might have a cached version of the package. you can use `npx @foxgove/...@latest ...` to always run the latest version

**Comment by amacneil** [comment]
Apparently percent encoding characters is not mandatory. It looks weird to me having `://` inside URL GET params, but I don't feel strongly about it.

**Pull request closed without merging**
